#
# SystemWrapper solution
# AppVeyor configuration
#

version: 0.9.1.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

platform: Any CPU
configuration: Release

build_script: build.bat

#artifacts:
#  - path: 'publish\*.nupkg'

assembly_info:
  patch: true
  file: 'Build\AssemblySharedInfo.cs'
  assembly_version: "{version}"
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - SystemWrapper.Tests.dll

cache:
  - packages -> **\packages.config

deploy:
  - provider: NuGet
    api_key: 
      secure: jINaEHhYh83PTuZYPwnkoTDUMB+pTz6UMmeqkWeRnqtZXIuX/Nd3Fyu197viK/vR
    on:
      appveyor_repo_tag: true
